### PR TITLE
Added bio to PublicUserProjection

### PR DESCRIPTION
**Pull request by BanTheNons**

### CODE REVIEW

**Comment by BanTheNons** [comment]
Oops, I forgot about the fact that bots can't actually access bios. Sorry!

**Comment by Flam3rboy** [comment]
too fast xD

**Comment by BanTheNons** [comment]
wait what
image

**Comment by Flam3rboy** [comment]
not a problem tho, as it just returns null for bots

**Comment by Flam3rboy** [comment]
but afaik oauth2 applications and bots can have about me sections

**Comment by Flam3rboy** [comment]
image

**Comment by Flam3rboy** [comment]
image

**Comment by BanTheNons** [comment]
They do, it's just the description of the application. Discord doesn't let bots or oauth applications access this property for security reasons tho

**Comment by Flam3rboy** [comment]
So what properties should be accessible by bots and what not

**Comment by BanTheNons** [comment]
image
everything in there except `bio` should be null

**Comment by BanTheNons** [comment]
There also has to be the user property - I guess I'll create another PR for it

**Pull request closed without merging**
