### PR TITLE
Merge fosscord/fosscord-server-util/ with afeuerstein/fosscord-server-util/

### PR DESCRIPTION
**Pull request by afeuerstein**
I fixed some mongoose deprecation warnings and a mongodb and mongoose version conflict. I also removed `dist/` from the repo and added it to `.gitignore`.

### CODE REVIEW

**Comment by veselcraft** [comment]
`.gitignore` is really helpful btw

**Comment by afeuerstein** [comment]
Oh, I just read pull request #1 .
As of my testing, the db still works wit urlParser and UnifiedTopology enabled.
If it isn't possible building `dist/` at installation time, could you please remove my first commit?

**Comment by Flam3rboy** [comment]
I'll have a look how to compile a specific node_module at ``npm run build`` in the api/gateway repo

**Comment by Flam3rboy** [comment]
btw. @afeuerstein whats your name on discord?

**Comment by afeuerstein** [comment]
> btw. @afeuerstein whats your name on discord?

I'm x_x#7177, already on the server

**Comment by Flam3rboy** [comment]
ok urlParser + UnifiedTopology work.
But I'm still getting another warning:
```
(node:27050) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
```

**Comment by afeuerstein** [comment]
I fixed that by upgrading mongoose and mongodb. Please run `npm i` to update your modules.

**Comment by afeuerstein** [comment]
Oh, you just did that yourself

**Pull request merged**
